# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Portcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_sea_port', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('is_bulk', models.BooleanField(default=False)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('custom_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('transportable_by_sea', models.BooleanField(default=True)),
                ('transportable_by_road', models.BooleanField(default=True)),
                ('transportable_by_air', models.BooleanField(default=True)),
                ('transportable_by_rail', models.BooleanField(default=True)),
            ],
        ),
    ]
