# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20180323_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origintoportroad',
            name='fare_box_density',
        ),
        migrations.RemoveField(
            model_name='porttodestinationroad',
            name='fare_box_density',
        ),
        migrations.RemoveField(
            model_name='porttodestinationsea',
            name='fare_box_density',
        ),
        migrations.AddField(
            model_name='calculatordata',
            name='customs_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatordata',
            name='gst_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatordata',
            name='insurance_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculatordata',
            name='port_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='calculatordata',
            name='port_to_dest_container_type',
            field=models.IntegerField(choices=[(1, "20'ST"), (2, "40'ST"), (3, 'Bulk 20k DWT'), (4, 'Bulk 40k DWT'), (5, 'Bulk 70k DWT')]),
        ),
        migrations.AlterField(
            model_name='origintoportair',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='origintoportrail',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='origintoportroad',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationair',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationroad',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationsea',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
    ]
