# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20180330_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatordata',
            name='port_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='origintoportair',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='origintoportrail',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='origintoportroad',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationair',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationroad',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
        migrations.AlterField(
            model_name='porttodestinationsea',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PortCity'),
        ),
    ]
